name: Deployment Workflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    # branches:
    #- testing
  pull_request:
    branches: [ "testing" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:       
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4 

        - name: Install dependencies
          run: npm install

           
          
        - name: Build Next.js app
          run: npm run build
