name: Deployment Workflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup NodeJs
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build
